[package]
name = "fyntr"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13"
actix-rt = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
bytes = "1"
env_logger = "0.11"
log = "0.4"
hickory-resolver = { version = "0.25", default-features = false, features = ["tokio", "system-config"] }
lru = "0.16"
idna = "1.1"
libc = "0.2"

[dev-dependencies]
quickcheck = "1"
