[package]
name = "fyntr"
version = "0.1.1"
edition = "2024"

[dependencies]
actix = "0.13"
actix-rt = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
bytes = "1"
env_logger = "0.11"
log = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }

[dev-dependencies]
quickcheck = "1"
