[package]
name = "fyntr"
version = "0.1.5"
edition = "2024"
description = "A minimal forward proxy to tame bursty outbound traffic."
license = "MIT"
repository = "https://github.com/Crux-One/Fyntr"
readme = "README.md"

[[bin]]
name = "fyntr"
path = "src/main.rs"

[dependencies]
actix = "0.13"
actix-rt = "2"
tokio = { version = "1.48", features = ["full"] }
anyhow = "1"
bytes = "1.11"
env_logger = "0.11"
log = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }

[dev-dependencies]
quickcheck = "1"
