[package]
name = "fyntr"
version = "0.2.8"
edition = "2024"
description = "A minimal forward proxy to tame bursty outbound traffic"
license = "MIT"
repository = "https://github.com/Crux-One/Fyntr"
readme = "README.md"

[[bin]]
name = "fyntr"
path = "src/main.rs"

[dependencies]
actix = "0.13"
actix-rt = "2"
tokio = { version = "1.49", features = ["full"] }
anyhow = "1"
bytes = "1.11.1"
clap = { version = "4.5.58", features = ["derive", "env"] }
env_logger = "0.11"
log = "0.4.29"

[target.'cfg(unix)'.dependencies]
rlimit = "0.11.0"

[dev-dependencies]
tokio = { version = "1.49", features = ["test-util"] }
quickcheck = "1"
